name    = "StraightLinePrograms"
uuid    = "42eed0b5-a112-4d56-a5b1-e566078f5bf3"
authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
version = "0.1.0"

[deps]
Test            = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extras]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"

[targets]
test = ["AbstractAlgebra"]

[compat]
julia           = "1"
AbstractAlgebra = "^0.9.1"
